import {
  Period,
  School,
  SchoolClass,
  Student,
  SociometricNomination,
  PeerBehavioralRating,
  User,
  NotificationItem,
  StudentQualitativeNote,
  ClassCounselorSummary,
  PasswordResetRequest,
} from '../types';

export const INITIAL_PERIODS: Period[] = [
  {
    id: 'period-2025-s1',
    name: 'Semester Ganjil 2025/2026',
    code: '2025-S1',
    academicYear: '2025/2026',
    semester: 1,
    cycleType: 'semester',
    status: 'ditutup',
    startDate: '2025-07-15',
    endDate: '2025-12-20',
    description: 'Pengambilan data baseline sosiometri awal tahun ajaran',
  },
  {
    id: 'period-2025-s2',
    name: 'Semester Genap 2025/2026',
    code: '2025-S2',
    academicYear: '2025/2026',
    semester: 2,
    cycleType: 'semester',
    status: 'ditutup',
    startDate: '2026-01-08',
    endDate: '2026-06-20',
    description: 'Pemantauan pasca intervensi bimbingan kelompok tahap 1',
  },
  {
    id: 'period-2026-s1',
    name: 'Semester Ganjil 2026/2027 (Aktif)',
    code: '2026-S1',
    academicYear: '2026/2027',
    semester: 1,
    cycleType: 'semester',
    status: 'aktif',
    startDate: '2026-07-15',
    endDate: '2026-12-20',
    description: 'Asesmen komprehensif Radar Sosial Ekologis berjalan',
  },
  {
    id: 'period-2026-tw1',
    name: 'Triwulan I 2026/2027 (Jul - Sep)',
    code: '2026-TW1',
    academicYear: '2026/2027',
    semester: 1,
    cycleType: 'triwulan',
    quarter: 1,
    status: 'ditutup',
    startDate: '2026-07-15',
    endDate: '2026-09-30',
    description: 'Survei orientasi adaptasi siswa baru & pembentukan kelompok belajar',
  },
  {
    id: 'period-2026-tw2',
    name: 'Triwulan II 2026/2027 (Okt - Des)',
    code: '2026-TW2',
    academicYear: '2026/2027',
    semester: 1,
    cycleType: 'triwulan',
    quarter: 2,
    status: 'draft',
    startDate: '2026-10-01',
    endDate: '2026-12-20',
    description: 'Pemetaan stabilitas klik pertemanan menjelang asesmen akhir semester',
  },
  {
    id: 'period-2027-s2',
    name: 'Semester Genap 2026/2027',
    code: '2027-S2',
    academicYear: '2026/2027',
    semester: 2,
    cycleType: 'semester',
    status: 'draft',
    startDate: '2027-01-05',
    endDate: '2027-06-18',
    description: 'Evaluasi tindak lanjut konseling individual dan bimbingan teman sebaya',
  },
];

export const INITIAL_SCHOOLS: School[] = [
  {
    id: 'sch-mtsn2-bangka',
    name: 'MTs Negeri 2 Bangka',
    npsn: '10901234',
    address: 'Jl. Pemuda No. 45, Sungailiat, Bangka Belitung',
    city: 'Kabupaten Bangka',
    type: 'Madrasah',
    totalClasses: 12,
    principalName: 'Drs. H. Ahmad Fauzi, M.Ag.',
    counselorName: 'Liengga Brian Darea, S.Sos.,Gr',
    phone: '(0717) 92345',
    status: 'aktif',
    theme: {
      preset: 'navy_gold',
      primaryColor: '#0a2a4a',
      secondaryColor: '#0d3555',
      accentColor: '#f0c040',
      accentLight: '#f7d970',
      schoolBadge: 'Madrasah Hebat Bermartabat',
    },
  },
  {
    id: 'sch-smpn1-sungailiat',
    name: 'SMP Negeri 1 Sungailiat',
    npsn: '10905678',
    address: 'Jl. Jenderal Sudirman No. 12, Sungailiat',
    city: 'Kabupaten Bangka',
    type: 'SMP',
    totalClasses: 15,
    principalName: 'H. Hendra, M.Pd.',
    counselorName: 'Rina Marlina, S.Pd.',
    phone: '(0717) 91122',
    status: 'aktif',
    theme: {
      preset: 'royal_sapphire',
      primaryColor: '#0f2b5c',
      secondaryColor: '#1a3f7a',
      accentColor: '#38bdf8',
      accentLight: '#7dd3fc',
      schoolBadge: 'Sekolah Penggerak Berprestasi',
    },
  },
];

export const INITIAL_CLASSES: SchoolClass[] = [
  {
    id: 'cls-8a',
    schoolId: 'sch-mtsn2-bangka',
    name: 'Kelas 8A',
    grade: '8',
    academicYear: '2026/2027',
    homeroomTeacher: 'Budi Santoso, S.Pd.',
    counselorId: 'usr-guru-bk',
    counselorName: 'Liengga Brian Darea, S.Sos.,Gr',
    targetStudentCount: 30,
    description: 'Rombongan belajar unggulan sosiometri semester ganjil',
  },
  {
    id: 'cls-8b',
    schoolId: 'sch-mtsn2-bangka',
    name: 'Kelas 8B',
    grade: '8',
    academicYear: '2026/2027',
    homeroomTeacher: 'Nurul Hidayati, M.Pd.',
    counselorId: 'usr-guru-bk',
    counselorName: 'Liengga Brian Darea, S.Sos.,Gr',
    targetStudentCount: 28,
  },
  {
    id: 'cls-7a',
    schoolId: 'sch-mtsn2-bangka',
    name: 'Kelas 7A',
    grade: '7',
    academicYear: '2026/2027',
    homeroomTeacher: 'Dra. Endang Purwanti',
    counselorId: 'usr-guru-bk-2',
    counselorName: 'Dra. Siti Rahmawati, M.Pd.Kons',
    targetStudentCount: 32,
    description: 'Rombongan belajar tingkat 7',
  },
  {
    id: 'cls-9a',
    schoolId: 'sch-mtsn2-bangka',
    name: 'Kelas 9A',
    grade: '9',
    academicYear: '2026/2027',
    homeroomTeacher: 'Drs. Ahmad Mansur',
    counselorId: 'usr-guru-bk-3',
    counselorName: 'Ahmad Zaki, S.Pd.I, Gr',
    targetStudentCount: 32,
  },
  {
    id: 'cls-smp1-8a',
    schoolId: 'sch-smpn1-sungailiat',
    name: 'Kelas VIII-A (SMPN 1)',
    grade: '8',
    academicYear: '2026/2027',
    homeroomTeacher: 'Slamet Riyadi, S.Pd.',
    counselorId: 'usr-guru-bk-sungailiat',
    counselorName: 'Rina Marlina, S.Pd.',
    targetStudentCount: 30,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-guru-bk',
    name: 'Liengga Brian Darea, S.Sos.,Gr',
    email: 'gurubk@radarsosial.id',
    password: 'bk123456',
    role: 'guru_bk',
    schoolId: 'sch-mtsn2-bangka',
    schoolName: 'MTs Negeri 2 Bangka',
    assignedClassIds: ['cls-8a', 'cls-8b'],
    nip: '19880914 201503 1 002',
    phone: '0812-7890-1234',
    title: 'Guru Bimbingan dan Konseling (Koordinator Kelas 8)',
    status: 'active',
    createdAt: '2025-01-10',
  },
  {
    id: 'usr-guru-bk-2',
    name: 'Dra. Siti Rahmawati, M.Pd.Kons',
    email: 'siti.bk@radarsosial.id',
    password: 'bk123456',
    role: 'guru_bk',
    schoolId: 'sch-mtsn2-bangka',
    schoolName: 'MTs Negeri 2 Bangka',
    assignedClassIds: ['cls-7a'],
    nip: '19790614 200501 2 004',
    phone: '0813-7345-6677',
    title: 'Guru Bimbingan dan Konseling (Kelas 7)',
    status: 'active',
    createdAt: '2025-01-12',
  },
  {
    id: 'usr-guru-bk-3',
    name: 'Ahmad Zaki, S.Pd.I, Gr',
    email: 'zaki.bk@radarsosial.id',
    password: 'bk123456',
    role: 'guru_bk',
    schoolId: 'sch-mtsn2-bangka',
    schoolName: 'MTs Negeri 2 Bangka',
    assignedClassIds: ['cls-9a'],
    nip: '19910419 201903 1 007',
    phone: '0821-7788-9900',
    title: 'Guru Bimbingan dan Konseling (Kelas 9)',
    status: 'active',
    createdAt: '2025-01-15',
  },
  {
    id: 'usr-admin',
    name: 'Dr. Diah Meitikasari, M.Psi.',
    email: 'admin@radarsosial.id',
    password: 'admin123456',
    role: 'admin',
    schoolId: 'sch-mtsn2-bangka',
    schoolName: 'Psychosophia Behavioral Lab',
    title: 'Super-Administrator Sistem & Peneliti Utama',
    status: 'active',
    createdAt: '2024-12-01',
  },
  {
    id: 'usr-kepsek',
    name: 'Drs. H. Ahmad Fauzi, M.Ag.',
    email: 'kepsek@radarsosial.id',
    password: 'kepsek123456',
    role: 'kepala_sekolah',
    schoolId: 'sch-mtsn2-bangka',
    schoolName: 'MTs Negeri 2 Bangka',
    nip: '19740512 199903 1 002',
    phone: '0813-6712-4455',
    title: 'Kepala Sekolah / Madrasah',
    status: 'active',
    createdAt: '2025-01-05',
  },
  {
    id: 'usr-guru-bk-sungailiat',
    name: 'Rina Marlina, S.Pd.',
    email: 'bk.sungailiat@radarsosial.id',
    password: 'bk123456',
    role: 'guru_bk',
    schoolId: 'sch-smpn1-sungailiat',
    schoolName: 'SMP Negeri 1 Sungailiat',
    assignedClassIds: ['cls-smp1-8a'],
    nip: '19830412 200801 2 003',
    phone: '0821-8899-7711',
    title: 'Guru Bimbingan dan Konseling (BK)',
    status: 'active',
    createdAt: '2025-02-01',
  },
  {
    id: 'usr-kepsek-sungailiat',
    name: 'H. Hendra, M.Pd.',
    email: 'kepsek.sungailiat@radarsosial.id',
    password: 'kepsek123456',
    role: 'kepala_sekolah',
    schoolId: 'sch-smpn1-sungailiat',
    schoolName: 'SMP Negeri 1 Sungailiat',
    nip: '19710315 199602 1 001',
    title: 'Kepala Sekolah',
    status: 'active',
    createdAt: '2025-02-01',
  },
];

export const INITIAL_PASSWORD_REQUESTS: PasswordResetRequest[] = [
  {
    id: 'req-01',
    userId: 'usr-guru-bk-2',
    userName: 'Dra. Siti Rahmawati, M.Pd.Kons',
    userEmail: 'siti.bk@radarsosial.id',
    userRole: 'guru_bk',
    schoolName: 'MTs Negeri 2 Bangka',
    requestedAt: '2026-09-14T09:15:00Z',
    reason: 'Lupa password lama setelah pembaruan semester baru, mohon reset password.',
    proposedPassword: 'SitiBaru2026!',
    status: 'pending',
  },
];

export const INITIAL_STUDENT_NOTES: StudentQualitativeNote[] = [
  {
    id: 'note-01',
    studentId: 's-02',
    studentName: 'Budi Pratama',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-10',
    context: 'Konseling Individu',
    content: 'Budi menyampaikan merasa sering diabaikan saat kerja kelompok dan kerap disindir ketika menyampaikan pendapat di depan kelas. Mengalami kecemasan relasional dan merasa enggan berangkat sekolah di hari Kamis.',
    thematicCategory: 'Kerentanan Viktimisasi / Isolasi Sebaya',
    sentiment: 'kritis',
    keywords: ['cemas', 'diabaikan', 'enggan sekolah', 'disindir', 'dijauhi'],
    aiInsight: 'Analisis Semantik LLM: Pola narasi mengindikasikan rasa ketidaknyamanan relasional dan risiko isolasi aktif. Direkomendasikan proteksi dini dan pendampingan konseling individual terstruktur.',
    createdAt: '2026-09-10T08:30:00Z',
  },
  {
    id: 'note-02',
    studentId: 's-02',
    studentName: 'Budi Pratama',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-12',
    context: 'Observasi Kelas',
    content: 'Saat diskusi kelompok IPA, kelompok meja belakang tampak enggan membagi lembar kerja kepada Budi. Budi memilih menunduk dan tidak aktif berinteraksi.',
    thematicCategory: 'Kerentanan Viktimisasi / Isolasi Sebaya',
    sentiment: 'kritis',
    keywords: ['ditolak', 'menunduk', 'enggan', 'diabaikan'],
    aiInsight: 'Analisis Semantik LLM: Pola penolakan aktif (peer rejection) di lingkungan belajar terkonfirmasi secara observasional. Perlu penataan kelompok kooperatif berstruktur adil.',
    createdAt: '2026-09-12T10:15:00Z',
  },
  {
    id: 'note-03',
    studentId: 's-05',
    studentName: 'Erna Susilowati',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-08',
    context: 'Observasi Kelas',
    content: 'Erna sangat jarang memulai percakapan spontan dengan teman sebangku. Saat istirahat tetap berada di dalam kelas membaca buku sendirian tanpa lingkaran sosial tetap.',
    thematicCategory: 'Kecemasan Sosial & Penarikan Diri',
    sentiment: 'perlu_perhatian',
    keywords: ['membaca sendiri', 'diam', 'menyendiri', 'pasif'],
    aiInsight: 'Analisis Semantik LLM: Siswa terindikasi mengalami inhibisi sosial saat konteks Observasi Kelas. Disarankan pendekatan personal yang suportif dan pengelompokan dengan figur sebaya yang ramah.',
    createdAt: '2026-09-08T11:00:00Z',
  },
  {
    id: 'note-04',
    studentId: 's-05',
    studentName: 'Erna Susilowati',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-11',
    context: 'Konseling Individu',
    content: 'Erna mengaku merasa malu dan takut salah bicara jika diajak mengobrol dalam kelompok besar. Tidak memiliki sahabat akrab tempat bertukar cerita di kelas, merasa lebih nyaman menyendiri.',
    thematicCategory: 'Kecemasan Sosial & Penarikan Diri',
    sentiment: 'perlu_perhatian',
    keywords: ['takut', 'malu', 'sahabat', 'menyendiri', 'diam'],
    aiInsight: 'Analisis Semantik LLM: Status terabaikan (neglected) berakar dari rasa rendah diri dan kekhawatiran evaluasi negatif. Program peer-buddying 1-on-1 sangat direkomendasikan.',
    createdAt: '2026-09-11T09:30:00Z',
  },
  {
    id: 'note-05',
    studentId: 's-04',
    studentName: 'Dimas Aditya Nugraha',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-09',
    context: 'Bimbingan Kelompok',
    content: 'Dimas menunjukkan kepekaan sosial tinggi, secara aktif mengajak teman yang duduk sendirian untuk bergabung saat pemilihan anggota regu olahraga. Bersikap ramah, adil, dan merangkul tanpa membedakan.',
    thematicCategory: 'Kepemimpinan Prokolektif & Inklusi',
    sentiment: 'positif',
    keywords: ['merangkul', 'pemimpin', 'mengajak', 'inklusif', 'adil', 'ramah'],
    aiInsight: 'Analisis Semantik LLM: Siswa memperlihatkan modalitas sosial prososial unggul. Sangat tepat diberdayakan sebagai pendamping sebaya (peer buddy) untuk merangkul rekan yang pasif.',
    createdAt: '2026-09-09T09:45:00Z',
  },
  {
    id: 'note-06',
    studentId: 's-04',
    studentName: 'Dimas Aditya Nugraha',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-13',
    context: 'Interaksi Informal / Istirahat',
    content: 'Terlihat mendamaikan perdebatan kecil saat antre di kantin dengan gaya bicara santun dan humoris. Mampu menjadi jembatan komunikasi antar kelompok siswa tanpa memihak.',
    thematicCategory: 'Kepemimpinan Prokolektif & Inklusi',
    sentiment: 'positif',
    keywords: ['mendamaikan', 'menolong', 'pemimpin', 'ramah'],
    aiInsight: 'Analisis Semantik LLM: Kapasitas arbitrase dan resolusi konflik sebaya yang matang. Menjadi jangkar penyeimbang iklim sosial rombel.',
    createdAt: '2026-09-13T10:10:00Z',
  },
  {
    id: 'note-07',
    studentId: 's-06',
    studentName: 'Fajar Hidayatullah',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-11',
    context: 'Observasi Kelas',
    content: 'Terjadi friksi verbal di lapangan olahraga karena candaan sarkas yang memicu ketersinggungan rekan setim. Fajar memiliki energi sosial tinggi namun impulsif saat menanggapi situasi kompetitif.',
    thematicCategory: 'Agresivitas Reaktif & Regulasi Emosi',
    sentiment: 'kritis',
    keywords: ['friksi', 'impulsif', 'marah', 'sarkas', 'emosi meledak'],
    aiInsight: 'Analisis Semantik LLM: Reaksi emosional dan friksi antar-sebaya perlu difasilitasi melalui latihan komunikasi asertif tanpa menyalahkan.',
    createdAt: '2026-09-11T14:30:00Z',
  },
  {
    id: 'note-08',
    studentId: 's-06',
    studentName: 'Fajar Hidayatullah',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-14',
    context: 'Konseling Individu',
    content: 'Fajar menyadari gayanya yang sering mengejek teman lain membuat beberapa rekan menjauh. Bersedia membuat komitmen kontrak perilaku untuk mengendalikan emosi dan menjaga ketertiban kelas.',
    thematicCategory: 'Agresivitas Reaktif & Regulasi Emosi',
    sentiment: 'perlu_perhatian',
    keywords: ['mengejek', 'gaduh', 'regulasi emosi', 'impulsif'],
    aiInsight: 'Analisis Semantik LLM: Kesadaran diri (*self-awareness*) mulai terbangun positif. Memerlukan penguatan konsistensi pada modul pengelolaan amarah.',
    createdAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'note-09',
    studentId: 's-01',
    studentName: 'Alya Rahma Azzahra',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-07',
    context: 'Observasi Kelas',
    content: 'Alya dan Citra memperlihatkan kolaborasi belajar yang sangat kompak dan saling mendukung. Aktif membantu menerangkan materi rumus kepada teman semeja dengan sabar dan tulus.',
    thematicCategory: 'Dukungan & Resiprositas Pertemanan',
    sentiment: 'positif',
    keywords: ['kompak', 'mendukung', 'belajar bersama', 'sahabat', 'resiprok'],
    aiInsight: 'Analisis Semantik LLM: Ikatan dyad yang sehat dan prososial. Menjadi model pertemanan suportif yang dapat ditularkan dalam bimbingan klasikal.',
    createdAt: '2026-09-07T08:20:00Z',
  },
  {
    id: 'note-10',
    studentId: 's-16',
    studentName: 'Putri Ayu Wandira',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-10',
    context: 'Interaksi Informal / Istirahat',
    content: 'Terlihat membentuk kelompok lingkaran bermain tertutup (klik 4 siswi) yang cenderung membatasi siswi lain ikut bergabung dalam obrolan dan kerap membeda-bedakan kelompok bermain.',
    thematicCategory: 'Klik Tertutup & Eksklusivitas Kelompok',
    sentiment: 'perlu_perhatian',
    keywords: ['klik', 'eksklusif', 'geng', 'terkotak', 'membeda-bedakan'],
    aiInsight: 'Analisis Semantik LLM: Eksklusivitas pergaulan memicu jarak relasional di kelas. Perlu perancangan aktivitas kolaboratif terarah lintas kelompok.',
    createdAt: '2026-09-10T12:15:00Z',
  },
  {
    id: 'note-11',
    studentId: 's-13',
    studentName: 'Muhammad Rizky Ramadhan',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-12',
    context: 'Observasi Kelas',
    content: 'Rizky aktif sebagai penggerak tim belajar komputer, selalu bersedia berbagi giliran perangkat secara adil dan merangkul rekan yang lambat memahami instruksi praktikum.',
    thematicCategory: 'Kepemimpinan Prokolektif & Inklusi',
    sentiment: 'positif',
    keywords: ['pemimpin', 'menolong', 'adil', 'merangkul', 'berbagi'],
    aiInsight: 'Analisis Semantik LLM: Profil kepemimpinan teknis yang inklusif. Efektif mendampingi rekan kelompok yang membutuhkan dorongan percaya diri.',
    createdAt: '2026-09-12T13:40:00Z',
  },
  {
    id: 'note-12',
    studentId: 's-19',
    studentName: 'Siti Maisaroh',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-13',
    context: 'Konseling Individu',
    content: 'Siti merasa nyaman dengan 2 sahabat karibnya di kelas, namun mengeluhkan adanya pembentukan klik eksklusif meja depan yang membuatnya enggan berbaur lebih luas.',
    thematicCategory: 'Klik Tertutup & Eksklusivitas Kelompok',
    sentiment: 'perlu_perhatian',
    keywords: ['sahabat', 'klik', 'eksklusif', 'terkotak', 'enggan'],
    aiInsight: 'Analisis Semantik LLM: Persepsi polarisasi kelompok dapat diurai melalui rotasi berkala penataan tempat duduk dan penugasan proyek silang.',
    createdAt: '2026-09-13T14:10:00Z',
  },
  {
    id: 'note-13',
    studentId: 's-10',
    studentName: 'Jaka Tarub Pratama',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-14',
    context: 'Konseling Individu',
    content: 'Catatan Curahan Hati Siswa ke Guru BK: "Pak/Bu, saya bingung kalau jam istirahat mau gabung main bola sering dibilang operan saya jelek sama kelompok anak laki-laki lain. Akhirnya saya lebih memilih duduk di dekat perpustakaan sendirian daripada memicu keributan."',
    thematicCategory: 'Kecemasan Sosial & Penarikan Diri',
    sentiment: 'perlu_perhatian',
    keywords: ['bingung', 'tersisih', 'diejek', 'menghindar', 'curhat siswa', 'cemas'],
    aiInsight: 'Analisis Semantik LLM: Siswa mengalami penarikan diri defensif akibat penolakan verbal ringan saat aktivitas non-akademik. Disarankan bimbingan asertivitas dan fasilitasi inklusi dalam tim bermain terstruktur.',
    createdAt: '2026-09-14T09:20:00Z',
  },
  {
    id: 'note-14',
    studentId: 's-14',
    studentName: 'Nabila Putri Cahyani',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-14',
    context: 'Laporan Teman Sebaya',
    content: 'Catatan Siswa ke Guru BK (Laporan Kepedulian Sebaya): Nabila mendatangi ruang BK mengutarakan kepedulian terhadap Erna yang terlihat semakin sering menyendiri dan tidak berani membaur. Nabila meminta saran konselor bagaimana cara mendekatinya secara lembut agar Erna merasa diterima.',
    thematicCategory: 'Dukungan & Resiprositas Pertemanan',
    sentiment: 'positif',
    keywords: ['peduli', 'merangkul', 'empati', 'sahabat', 'resiprok', 'dukungan sebaya'],
    aiInsight: 'Analisis Semantik LLM: Sikap empati dan inisiatif prososial tinggi dari teman sebaya. Nabila merupakan aset strategis untuk dipasangkan sebagai "Peer Buddy" bagi siswa berkategori neglected.',
    createdAt: '2026-09-14T10:45:00Z',
  },
  {
    id: 'note-15',
    studentId: 's-18',
    studentName: 'Rangga Danendra',
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    authorName: 'Liengga Brian Darea, S.Sos.,Gr',
    authorRole: 'guru_bk',
    date: '2026-09-15',
    context: 'Konseling Individu',
    content: 'Catatan Curahan Hati Siswa ke Guru BK: "Saya merasa tertekan harus selalu menuruti kemauan lingkaran teman nongkrong, kalau saya menolak diajak nongkrong sepulang sekolah saya diancam tidak diajak mengobrol lagi di kelas."',
    thematicCategory: 'Klik Tertutup & Eksklusivitas Kelompok',
    sentiment: 'kritis',
    keywords: ['tekanan kelompok', 'peer pressure', 'diancam', 'tertekan', 'konformitas'],
    aiInsight: 'Analisis Semantik LLM: Adanya fenomena konformitas destruktif (peer pressure) dan kontrol koersif dalam klik pergaulan. Dibutuhkan penguatan otonomi pribadi dan mediasi batasan relasi yang sehat.',
    createdAt: '2026-09-15T08:15:00Z',
  },
];

export const INITIAL_CLASS_SUMMARIES: Record<string, ClassCounselorSummary> = {
  'cls-8a_period-2026-s1': {
    classId: 'cls-8a',
    periodId: 'period-2026-s1',
    counselorReflection: `Secara keseluruhan dinamika sosial Kelas 8A Semester Ganjil 2026/2027 menunjukkan kohesi yang cukup baik namun memiliki titik kerentanan polarisasi sub-grup dan beberapa individu yang terisolasi. 

Hasil pemetaan kuantitatif sosiometri Coie-Dodge dan triangulasi catatan kualitatif tematik menunjukkan:
1. Terdeteksi satu siswa mengalami penolakan aktif (Budi Pratama / Status Rejected) yang membutuhkan proteksi relasi dan intervensi konseling individual intensif.
2. Terdapat siswa yang mengalami penarikan diri pasif (Erna Susilowati / Status Neglected) yang perlu didampingi melalui program buddying satu-satu.
3. Teridentifikasi figur kepemimpinan prososial yang kuat (Dimas Aditya Nugraha / Status Popular) yang siap diberdayakan sebagai Peer Counselor kelas.
4. Terdapat kecenderungan klik pergaulan tertutup di kalangan siswi yang disarankan diurai melalui rotasi berkala tempat duduk dan proyek belajar kooperatif lintas-kelompok.`,
    updatedAt: '2026-09-14T11:00:00Z',
    updatedBy: 'Liengga Brian Darea, S.Sos.,Gr',
  },
};

export const INITIAL_STUDENTS_8A: Student[] = [
  { id: 's-01', nis: '20260801', name: 'Alya Rahma Azzahra', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-02', nis: '20260802', name: 'Budi Pratama', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' }, // Target priority: Rejected
  { id: 's-03', nis: '20260803', name: 'Citra Dewi Lestari', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-04', nis: '20260804', name: 'Dimas Aditya Nugraha', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' }, // Popular
  { id: 's-05', nis: '20260805', name: 'Erna Susilowati', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' }, // Neglected
  { id: 's-06', nis: '20260806', name: 'Fajar Hidayatullah', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' }, // Controversial
  { id: 's-07', nis: '20260807', name: 'Gita Savitri Maharani', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-08', nis: '20260808', name: 'Hafiiz Al-Farisi', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-09', nis: '20260809', name: 'Indah Permata Sari', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-10', nis: '20260810', name: 'Jaka Tarub Pratama', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-11', nis: '20260811', name: 'Kevin Prasetya', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-12', nis: '20260812', name: 'Laras Sati Wulandari', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-13', nis: '20260813', name: 'Muhammad Rizky Ramadhan', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-14', nis: '20260814', name: 'Nabila Putri Cahyani', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-15', nis: '20260815', name: 'Oki Setiawan', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-16', nis: '20260816', name: 'Putri Ayu Wandira', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-17', nis: '20260817', name: 'Qori Anjani Fitria', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-18', nis: '20260818', name: 'Rangga Danendra', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-19', nis: '20260819', name: 'Siti Maisaroh', gender: 'P', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
  { id: 's-20', nis: '20260820', name: 'Taufiq Ismail', gender: 'L', classId: 'cls-8a', className: 'Kelas 8A', schoolId: 'sch-mtsn2-bangka' },
];

// Helper to seed nominations for 8A in current period (period-2026-s1)
export function generateSeedNominations(periodId: string): SociometricNomination[] {
  const noms: SociometricNomination[] = [];
  let idCounter = 1;

  // Pattern engineered to produce clear Coie & Dodge statuses:
  // s-04 (Dimas Aditya): Popular (high likes, 0 dislikes)
  // s-02 (Budi Pratama): Rejected (1 like, 7 dislikes)
  // s-05 (Erna Susilowati): Neglected (0 likes, 0 dislikes - invisible)
  // s-06 (Fajar Hidayatullah): Controversial (5 likes, 5 dislikes)
  // Others: Average distribution

  const likesMapping: Record<string, string[]> = {
    's-01': ['s-04', 's-03', 's-07'],
    's-02': ['s-04', 's-08', 's-13'],
    's-03': ['s-01', 's-04', 's-09'],
    's-04': ['s-08', 's-10', 's-01'],
    's-05': ['s-01', 's-03', 's-09'],
    's-06': ['s-04', 's-11', 's-18'],
    's-07': ['s-01', 's-03', 's-14'],
    's-08': ['s-04', 's-06', 's-13'],
    's-09': ['s-03', 's-04', 's-12'],
    's-10': ['s-04', 's-08', 's-11'],
    's-11': ['s-06', 's-10', 's-18'],
    's-12': ['s-04', 's-09', 's-14'],
    's-13': ['s-04', 's-08', 's-06'],
    's-14': ['s-01', 's-07', 's-12'],
    's-15': ['s-04', 's-06', 's-13'],
    's-16': ['s-03', 's-04', 's-17'],
    's-17': ['s-01', 's-16', 's-19'],
    's-18': ['s-06', 's-11', 's-04'],
    's-19': ['s-17', 's-03', 's-04'],
    's-20': ['s-04', 's-08', 's-13'],
  };

  const dislikesMapping: Record<string, string[]> = {
    's-01': ['s-02'],
    's-03': ['s-02', 's-06'],
    's-04': ['s-06'],
    's-07': ['s-02'],
    's-08': ['s-02', 's-06'],
    's-09': ['s-02'],
    's-10': ['s-02'],
    's-11': ['s-02'],
    's-12': ['s-06'],
    's-13': ['s-06'],
    's-14': ['s-02'],
    's-15': ['s-06'],
    's-16': ['s-02'],
    's-18': ['s-02'],
  };

  // Generate both 'belajar' and 'bermain'
  for (const [nominator, targets] of Object.entries(likesMapping)) {
    targets.forEach((target, idx) => {
      noms.push({
        id: `nom-${idCounter++}`,
        periodId,
        classId: 'cls-8a',
        studentId: nominator,
        targetId: target,
        criteria: idx % 2 === 0 ? 'belajar' : 'bermain',
        type: 'like',
      });
    });
  }

  for (const [nominator, targets] of Object.entries(dislikesMapping)) {
    targets.forEach((target, idx) => {
      noms.push({
        id: `nom-${idCounter++}`,
        periodId,
        classId: 'cls-8a',
        studentId: nominator,
        targetId: target,
        criteria: idx % 2 === 0 ? 'belajar' : 'bermain',
        type: 'dislike',
      });
    });
  }

  return noms;
}

export function generateSeedBehavioralRatings(periodId: string): PeerBehavioralRating[] {
  // Prosocial, Aggressive, Withdrawn, Victimization, Hyperactive (scale 1-10 or peer votes)
  return [
    { id: 'b-01', periodId, classId: 'cls-8a', studentId: 's-01', prosocial: 8, aggressive: 1, withdrawn: 2, victimization: 1, hyperactive: 2 },
    // Budi Pratama: High victimization + withdrawn (Passive Victim / Rejected)
    { id: 'b-02', periodId, classId: 'cls-8a', studentId: 's-02', prosocial: 2, aggressive: 3, withdrawn: 8, victimization: 9, hyperactive: 4 },
    { id: 'b-03', periodId, classId: 'cls-8a', studentId: 's-03', prosocial: 7, aggressive: 1, withdrawn: 2, victimization: 1, hyperactive: 2 },
    // Dimas Aditya: High prosocial (Popular-Prososial)
    { id: 'b-04', periodId, classId: 'cls-8a', studentId: 's-04', prosocial: 9, aggressive: 1, withdrawn: 1, victimization: 0, hyperactive: 3 },
    // Erna Susilowati: High withdrawn, very low social impact (Isolated / Neglected)
    { id: 'b-05', periodId, classId: 'cls-8a', studentId: 's-05', prosocial: 3, aggressive: 1, withdrawn: 9, victimization: 3, hyperactive: 1 },
    // Fajar Hidayatullah: High aggressive + moderate prosocial (Bistrategic / Controversial Leader)
    { id: 'b-06', periodId, classId: 'cls-8a', studentId: 's-06', prosocial: 5, aggressive: 8, withdrawn: 1, victimization: 2, hyperactive: 8 },
    { id: 'b-07', periodId, classId: 'cls-8a', studentId: 's-07', prosocial: 6, aggressive: 2, withdrawn: 3, victimization: 1, hyperactive: 2 },
    { id: 'b-08', periodId, classId: 'cls-8a', studentId: 's-08', prosocial: 7, aggressive: 2, withdrawn: 2, victimization: 1, hyperactive: 3 },
    { id: 'b-09', periodId, classId: 'cls-8a', studentId: 's-09', prosocial: 6, aggressive: 1, withdrawn: 3, victimization: 2, hyperactive: 2 },
    { id: 'b-10', periodId, classId: 'cls-8a', studentId: 's-10', prosocial: 5, aggressive: 3, withdrawn: 2, victimization: 2, hyperactive: 4 },
    { id: 'b-11', periodId, classId: 'cls-8a', studentId: 's-11', prosocial: 4, aggressive: 5, withdrawn: 2, victimization: 2, hyperactive: 5 },
    { id: 'b-12', periodId, classId: 'cls-8a', studentId: 's-12', prosocial: 6, aggressive: 1, withdrawn: 3, victimization: 1, hyperactive: 2 },
    { id: 'b-13', periodId, classId: 'cls-8a', studentId: 's-13', prosocial: 7, aggressive: 2, withdrawn: 2, victimization: 1, hyperactive: 3 },
    { id: 'b-14', periodId, classId: 'cls-8a', studentId: 's-14', prosocial: 6, aggressive: 2, withdrawn: 2, victimization: 1, hyperactive: 3 },
    { id: 'b-15', periodId, classId: 'cls-8a', studentId: 's-15', prosocial: 4, aggressive: 3, withdrawn: 4, victimization: 2, hyperactive: 3 },
    { id: 'b-16', periodId, classId: 'cls-8a', studentId: 's-16', prosocial: 5, aggressive: 2, withdrawn: 3, victimization: 1, hyperactive: 2 },
    { id: 'b-17', periodId, classId: 'cls-8a', studentId: 's-17', prosocial: 5, aggressive: 1, withdrawn: 4, victimization: 1, hyperactive: 2 },
    { id: 'b-18', periodId, classId: 'cls-8a', studentId: 's-18', prosocial: 4, aggressive: 6, withdrawn: 2, victimization: 2, hyperactive: 6 },
    { id: 'b-19', periodId, classId: 'cls-8a', studentId: 's-19', prosocial: 5, aggressive: 2, withdrawn: 3, victimization: 2, hyperactive: 3 },
    { id: 'b-20', periodId, classId: 'cls-8a', studentId: 's-20', prosocial: 6, aggressive: 2, withdrawn: 2, victimization: 1, hyperactive: 3 },
  ];
}

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Peringatan Dini EWS: Siswa Berisiko Tinggi',
    message: 'Siswa Budi Pratama (NIS: 20260802, Kelas 8A) terdeteksi masuk dalam status "Rejected" dengan 8 nominasi penolakan dan skor viktimisasi tinggi (9/10). Disarankan intervensi konseling individual segera.',
    type: 'warning',
    timestamp: '2026-09-13T08:30:00Z',
    read: false,
    targetRoles: ['guru_bk', 'kepala_sekolah'],
    studentId: 's-02',
    classId: 'cls-8a',
    severity: 'high',
  },
  {
    id: 'notif-2',
    title: 'Deteksi Siswa Terisolasi (Neglected)',
    message: 'Siswa Erna Susilowati (NIS: 20260805, Kelas 8A) memiliki social impact sangat rendah (Z_SI < -1.2) dengan tingkat menarik diri 9/10. Perlu program buddying kelompok belajar.',
    type: 'alert',
    timestamp: '2026-09-12T14:15:00Z',
    read: false,
    targetRoles: ['guru_bk'],
    studentId: 's-05',
    classId: 'cls-8a',
    severity: 'medium',
  },
  {
    id: 'notif-3',
    title: 'Perubahan Signifikan Pola Interaksi Kelas 8A',
    message: 'Kepadatan relasi (density) Kelas 8A semester ini tercatat 0.22, turun dari semester lalu (0.28). Indeks iklim sosial beralih ke status Waspada.',
    type: 'info',
    timestamp: '2026-09-11T10:00:00Z',
    read: true,
    targetRoles: ['guru_bk', 'kepala_sekolah', 'admin'],
    classId: 'cls-8a',
    severity: 'medium',
  },
  {
    id: 'notif-4',
    title: 'Pembaruan Pantauan Anak untuk Orang Tua',
    message: 'Laporan asesmen sosio-emosional Budi Pratama untuk Semester Ganjil 2026/2027 telah diperbarui oleh Guru BK. Silakan simak panduan komunikasi ramah anak di rumah.',
    type: 'info',
    timestamp: '2026-09-13T09:00:00Z',
    read: false,
    targetRoles: ['orang_tua'],
    studentId: 's-02',
    severity: 'low',
  },
];
